const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const header=$('header'),nav=$('#navlinks'),menu=$('.menu'),cursor=$('.cursor');
addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>18),{passive:true});
addEventListener('pointermove',e=>{if(cursor){cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'}},{passive:true});
menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});
$$('#navlinks a,#navlinks button').forEach(x=>x.addEventListener('click',()=>{nav.classList.remove('open');menu?.setAttribute('aria-expanded','false')}));
const observer='IntersectionObserver'in window?new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');observer.unobserve(e.target)}}),{threshold:.1}):null;
$$('.reveal').forEach(x=>observer?observer.observe(x):x.classList.add('show'));

const stage={human:'Luca defines the real objective, acceptance standard, risk boundary and final judgement. This prevents the system from optimising for a polished answer instead of the actual outcome.',ai:'ACE accelerates breadth, comparison, synthesis, code assistance, documentation and iteration. Its output remains candidate work until it is validated.',tools:'Tools produce observable artefacts: repository changes, tests, documents, searches, structured records and workflow actions. Their real contracts limit what can be claimed.',proof:'The verifier separates source-reported success from independent evidence. Completion is accepted only when every required action and evidence field is satisfied.'};
$$('[data-stage]').forEach(b=>b.addEventListener('click',()=>{$$('[data-stage]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#stage-detail').textContent=stage[b.dataset.stage]}));

const checks={claim:$('#claim'),success:$('#success'),message:$('#message-id'),recipient:$('#recipient'),rollback:$('#rollback')};
const cases={verified:[1,1,1,1,0],missing:[1,1,0,1,0],failed:[1,0,0,0,0],rollback:[1,1,1,1,1],silent:[0,1,1,1,0]};
$$('[data-case]').forEach(b=>b.addEventListener('click',()=>{$$('[data-case]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const v=cases[b.dataset.case];Object.values(checks).forEach((x,i)=>x.checked=!!v[i]);evaluate()}));
function evaluate(){
 const v={claim:checks.claim.checked,success:checks.success.checked,message:checks.message.checked,recipient:checks.recipient.checked,rollback:checks.rollback.checked};
 let title,copy,tone;
 if(v.rollback){title='FAILED';copy='A later failure or rollback overrides the earlier success event.';tone='red'}
 else if(!v.success){title='FAILED';copy='The latest required action is recorded as unsuccessful.';tone='red'}
 else if(v.message&&v.recipient){title='VERIFIED_COMPLETE';copy=v.claim?'Every required action and evidence field is present in the latest successful event.':'The task is proven complete even though the agent did not announce success.';tone='green'}
 else if(v.message||v.recipient){title='PARTIAL';copy='The action appears successful, but only part of the required evidence is present.';tone='gold'}
 else{title='UNVERIFIED';copy=v.claim?'The agent claims completion, but no required evidence fields prove it.':'Nothing is proven and no completion claim was made.';tone='violet'}
 $('#result-title').textContent=title;$('#result-copy').textContent=copy;$('#console-state').textContent='EVALUATED';
 const colors={green:['#72e2b3','rgba(114,226,179,.08)','rgba(114,226,179,.35)'],red:['#ff8e95','rgba(255,142,149,.08)','rgba(255,142,149,.35)'],gold:['#f0ca72','rgba(240,202,114,.08)','rgba(240,202,114,.35)'],violet:['#a77dff','rgba(167,125,255,.08)','rgba(167,125,255,.35)']},c=colors[tone];
 $('#result-light').style.background=`radial-gradient(circle,${c[0]},${c[1]} 50%,transparent 72%)`;$('#result-light').style.boxShadow=`0 0 50px ${c[2]}`;
 const rows=[['01','Completion claim',v.claim?'Agent reported success':'No success claim',v.claim?'OBSERVED':'ABSENT'],['02','Latest action',v.success?'send_email succeeded':'send_email failed',v.success?'PASS':'FAIL'],['03','message_id evidence',v.message?'Present':'Missing',v.message?'PASS':'MISSING'],['04','recipient evidence',v.recipient?'Present':'Missing',v.recipient?'PASS':'MISSING'],['05','Later event',v.rollback?'Failure / rollback overrides success':'No later invalidating event',v.rollback?'FAIL':'CLEAR']];
 $('#trace').innerHTML='';rows.forEach(r=>{const li=document.createElement('li'),i=document.createElement('i'),d=document.createElement('div'),s=document.createElement('strong'),p=document.createElement('p'),b=document.createElement('b');i.textContent=r[0];s.textContent=r[1];p.textContent=r[2];b.textContent=r[3];d.append(s,p);li.append(i,d,b);$('#trace').append(li)});
}
$('#evaluate')?.addEventListener('click',evaluate);if(checks.claim)evaluate();

const caps={agent:['Evaluate AI agents','Define acceptance contracts, evidence fields, failure cases and recovery rules; build deterministic evaluators; preserve raw traces separately from derived judgements; and produce reproducible result bundles.'],workflow:['Design safer AI workflows','Map the real process, allocate human and AI responsibilities, identify irreversible actions, create approval gates and test in shadow mode before expanding autonomy.'],research:['Decompose difficult research','Reduce a broad question into decision-relevant sub-claims, compare explanations, expose uncertainty and leave a clear next experiment or decision.'],prototype:['Build credible prototypes','Translate an idea into a Python harness, interactive web demonstration, test suite, architecture map or technical specification while keeping production claims separate.'],operations:['Improve operations','Find information loss, manual repetition, unclear ownership and broken handoffs; redesign around structured inputs, explicit outcomes and measurable checkpoints.'],governance:['Make AI decisions reviewable','Record sources, assumptions, decisions, actions, outcomes, errors and corrections so another person can understand what happened and what remains uncertain.']};
$$('[data-cap]').forEach(b=>b.addEventListener('click',()=>{$$('[data-cap]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const[t,p]=caps[b.dataset.cap];$('#cap-detail').innerHTML='<strong>'+t+'</strong><p>'+p+'</p>'}));

const nviews={flow:['Operating flow','The Nexus routes work through objective, context, AI reasoning, tools, validation, output and outcome review before anything becomes durable learning.',['Human objective and constraints lead','Tool contracts are treated as real limits','Validation comes before consequential action','Outcome and error feed the next iteration']],record:['Continuous Learning Record','A proposed durable record keeps decisions and failure lessons from disappearing when a chat or work session ends.',['Observation · Decision · Action · Outcome','Error · Correction · Confidence','Provenance · Reusable pattern · Next action','Temporary session state stays separate']],status:['Capability status discipline','Every component is labelled by what exists now rather than marketed as though the full architecture is already operational.',['Verified practice: observable artefacts','Prototype: working, not production hardened','Framework: structured design guiding work','Planned: intentional next step']]};
function setN(v){const[t,p,ls]=nviews[v];$('#nexus-detail').innerHTML='<h3>'+t+'</h3><p>'+p+'</p><ul>'+ls.map(x=>'<li>'+x+'</li>').join('')+'</ul>';$$('[data-nview]').forEach(b=>b.classList.toggle('active',b.dataset.nview===v))}
$$('[data-nview]').forEach(b=>b.addEventListener('click',()=>setN(b.dataset.nview)));if($('#nexus-detail'))setN('flow');
const nodes={objective:['Human Objective & Constraints','The outcome that matters, what is off-limits, who owns the decision and how completion will be judged.'],context:['Context & Knowledge','Source-tagged inputs, prior decisions, freshness, uncertainty and the limits of available information.'],reasoning:['AI Reasoning','Options, analysis, comparison and generation treated as candidate work requiring validation.'],tools:['Tools & Actions','The mechanisms that search, calculate, write, retrieve or change state; their contracts define what is possible.'],validation:['Validation & Risk','Evidence checks, failure taxonomy, approval, reversibility and blast-radius review.'],outputs:['Outputs & Delivery','Documents, code, prototypes, decisions or actions another person can inspect and use.'],outcomes:['Outcomes & Feedback','What happened compared with what was expected, including errors, corrections and stakeholder response.'],patterns:['Patterns & Continuity','Reusable methods and failure lessons preserved only after evidence supports them.']};
$$('.nnode').forEach(n=>{n.setAttribute('tabindex','0');n.setAttribute('role','button');const go=()=>{$$('.nnode').forEach(x=>x.classList.remove('active'));n.classList.add('active');const[t,p]=nodes[n.dataset.node];$('#nexus-detail').innerHTML='<h3>'+t+'</h3><p>'+p+'</p><p><span class="status framework">Framework node</span></p>'};n.addEventListener('click',go);n.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}})});

const modal=$('#cv-modal');function openCV(){modal?.classList.add('open');modal?.setAttribute('aria-hidden','false')}function closeCV(){modal?.classList.remove('open');modal?.setAttribute('aria-hidden','true')}
$$('[data-cv]').forEach(b=>b.addEventListener('click',openCV));$$('[data-close-cv]').forEach(b=>b.addEventListener('click',closeCV));$('#print-cv')?.addEventListener('click',()=>print());
addEventListener('keydown',e=>{if(e.key==='Escape'){closeCV();nav?.classList.remove('open');menu?.setAttribute('aria-expanded','false')}});