const $=(s,c=document)=>c.querySelector(s);const $$=(s,c=document)=>[...c.querySelectorAll(s)];
const esc=(v="")=>String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const header=$('[data-header]'),cursor=$('.cursor-field'),menu=$('[data-menu]'),nav=$('[data-nav]');
addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>18),{passive:true});
addEventListener('pointermove',e=>{if(cursor){cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'}},{passive:true});
menu?.addEventListener('click',()=>{const open=nav?.classList.toggle('open')??false;menu.setAttribute('aria-expanded',String(open))});
$$('#primary-nav a,#primary-nav button').forEach(x=>x.addEventListener('click',()=>{nav?.classList.remove('open');menu?.setAttribute('aria-expanded','false')}));
const io='IntersectionObserver'in window?new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.1}):null;$$('.reveal').forEach(x=>io?io.observe(x):x.classList.add('visible'));

const commandData={
 direction:{label:'HUMAN DIRECTION',status:'ACCOUNTABLE OWNER',sigil:'L',title:'Define the real objective and what counts as done.',description:'The work begins by separating the requested task from the actual operational outcome, then fixing the acceptance standard before implementation.',contributes:'Problem framing, challenge, risk ownership, prioritisation and final judgement.',boundary:'Legal, financial, reputational and public accountability stay human-owned.',artefacts:'Objective contract, risk boundary, decision record and approval state.'},
 ace:{label:'AI COPILOT',status:'CANDIDATE WORK',sigil:'A',title:'Expand, compare and turn intent into inspectable artefacts.',description:'ACE is the continuity name for the AI copilot used across the work. It accelerates research, code assistance, testing, architecture and documentation without owning the outcome.',contributes:'Breadth, synthesis, counterarguments, rapid iteration and structured continuity.',boundary:'Fluent output is not proof; private prompts and internal framework details are not published.',artefacts:'Draft code, diagrams, test plans, specifications and structured analysis.'},
 tools:{label:'OBSERVABLE EXECUTION',status:'CONTRACT-BOUNDED',sigil:'T',title:'Create state changes and artefacts another person can inspect.',description:'Tools search, calculate, write, retrieve or change state. Their real contracts define what can be done and what evidence can be collected.',contributes:'Files, tests, identifiers, logs, searches and bounded workflow actions.',boundary:'A receipt supports only the fields and postconditions the tool can genuinely evidence.',artefacts:'Test output, files, logs, identifiers, manifests and observed state.'},
 evidence:{label:'INDEPENDENT JUDGEMENT',status:'CANONICAL LAYER',sigil:'E',title:'Decide what can be claimed from observable reality.',description:'Source-reported success stays separate from independent evidence. Completion is accepted only when the required action and evidence fields are satisfied.',contributes:'Verification, mismatch detection, replay, falsification and explicit uncertainty.',boundary:'The system performing an action cannot silently redefine the proof standard after acting.',artefacts:'Canonical verdict, raw trace, limitation statement and replay bundle.'},
 continuity:{label:'DECISIONS & LEARNING',status:'DEVELOPING PRACTICE',sigil:'C',title:'Preserve decisions, corrections and the next useful action.',description:'Structured records keep context from disappearing across long projects while provisional ideas remain clearly labelled.',contributes:'Project state, provenance, correction history and reusable patterns.',boundary:'Only supported lessons become durable; private operating details stay private.',artefacts:'Decision log, evidence links, correction record and next action.'}
};
function showCommand(key){const d=commandData[key];if(!d)return;$$('[data-command-node]').forEach(b=>{const on=b.dataset.commandNode===key;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on))});$('#command-label').textContent=d.label;$('#command-status').textContent=d.status;$('#command-sigil').textContent=d.sigil;$('#command-title').textContent=d.title;$('#command-description').textContent=d.description;$('#command-contributes').textContent=d.contributes;$('#command-boundary').textContent=d.boundary;$('#command-artefacts').textContent=d.artefacts}
$$('[data-command-node]').forEach(b=>b.addEventListener('click',()=>showCommand(b.dataset.commandNode)));

$$('[data-capability]').forEach(item=>{const trigger=$('.capability-trigger',item),body=$('.capability-body',item);trigger?.addEventListener('click',()=>{const open=!item.classList.contains('open');$$('[data-capability]').forEach(other=>{other.classList.remove('open');$('.capability-trigger',other)?.setAttribute('aria-expanded','false');const ob=$('.capability-body',other);if(ob)ob.hidden=true});if(open){item.classList.add('open');trigger.setAttribute('aria-expanded','true');if(body)body.hidden=false}})});

const roleData={
 evaluation:{title:'AI Evaluation / Quality Analyst',summary:'A strong first assignment would be to turn recurring agent failures into a structured evaluation suite and evidence-backed findings report.',proof:[['Current evidence','Completion Verifier + controlled Arena'],['First output','Acceptance contract and case suite'],['Team value','Fewer unsupported success claims']]},
 applied:{title:'Applied AI / Automation Specialist',summary:'A realistic first assignment would map one high-friction workflow, identify where AI adds value, and build a narrow shadow-mode prototype with human approval gates.',proof:[['Current evidence','Workflow and recovery design'],['First output','Narrow prototype + runbook'],['Team value','Safer, faster operational learning']]},
 deployment:{title:'AI Deployment / Implementation Associate',summary:'A realistic first assignment would translate a team requirement into testable integration criteria, support implementation, and document failure and handoff behaviour.',proof:[['Current evidence','Tool contracts and verification'],['First output','Integration checklist + test plan'],['Team value','Cleaner implementation handoff']]},
 operations:{title:'Technical Operations Analyst',summary:'A strong first assignment would trace a broken process across people and systems, locate ownership gaps, and define a measurable improvement pilot.',proof:[['Current evidence','Operational background'],['First output','Failure-surface and ownership map'],['Team value','Less lost work across handoffs']]},
 solutions:{title:'AI Product / Solutions Associate',summary:'A credible first assignment would shape a customer or internal problem, build an honest demonstration, and explain exactly what the prototype proves and what it does not.',proof:[['Current evidence','Interactive technical demos'],['First output','Problem brief + demonstrator'],['Team value','Better technical expectations']]},
 risk:{title:'Agentic Risk / AI Governance Analyst',summary:'A suitable developing assignment would review agent workflows for unsupported claims, missing approvals, poor provenance and unclear rollback behaviour.',proof:[['Current evidence','Evidence and boundary discipline'],['First output','Risk and control review'],['Team value','More reviewable AI decisions']]},
 research:{title:'Research Engineering Support',summary:'A developing assignment would decompose a difficult question, track assumptions and evidence, build a small experiment or simulation, and leave a decision-ready synthesis.',proof:[['Current evidence','Long-form research decomposition'],['First output','Claim map + prototype test'],['Team value','Faster route from question to experiment']]}
};
function showRole(key){const d=roleData[key];if(!d)return;$$('[data-role]').forEach(b=>b.classList.toggle('active',b.dataset.role===key));$('#role-fit-detail').innerHTML=`<div><small>PLAUSIBLE FIRST ASSIGNMENT</small><h3>${esc(d.title)}</h3></div><div><p>${esc(d.summary)}</p><div class="role-fit-proof">${d.proof.map(([a,b])=>`<div><strong>${esc(a)}</strong><span>${esc(b)}</span></div>`).join('')}</div></div>`}
$$('[data-role]').forEach(b=>b.addEventListener('click',()=>showRole(b.dataset.role)));

function showPanel(key){$$('[data-lab-target]').forEach(t=>{const on=t.dataset.labTarget===key;t.classList.toggle('active',on);t.setAttribute('aria-selected',String(on))});$$('[data-lab-panel]').forEach(p=>{const on=p.dataset.labPanel===key;p.classList.toggle('active',on);p.hidden=!on})}
$$('[data-lab-target]').forEach(t=>t.addEventListener('click',()=>showPanel(t.dataset.labTarget)));

const vi={claim:$('#v-claim'),success:$('#v-success'),message:$('#v-message'),recipient:$('#v-recipient'),rollback:$('#v-rollback')};
const presets={verified:[1,1,1,1,0],partial:[1,1,1,0,0],unverified:[1,1,0,0,0],failed:[1,0,0,0,0],rollback:[1,1,1,1,1]};
function evalVerifier(){const s=Object.fromEntries(Object.entries(vi).map(([k,x])=>[k,!!x?.checked]));let title,copy,color;if(s.rollback){title='FAILED';copy='A later failure or rollback invalidates the earlier successful event.';color='var(--red)'}else if(!s.success){title='FAILED';copy='The latest required action is unsuccessful.';color='var(--red)'}else if(s.message&&s.recipient){title='VERIFIED_COMPLETE';copy=s.claim?'Every required action and evidence field is present.':'The task is proven even without a completion claim.';color='var(--green)'}else if(s.message||s.recipient){title='PARTIAL';copy='The action appears successful, but only part of the required evidence is present.';color='var(--gold)'}else{title='UNVERIFIED';copy=s.claim?'The system claims completion without the required evidence.':'Nothing is proven and no completion claim was made.';color='var(--violet)'}$('#verifier-title').textContent=title;$('#verifier-copy').textContent=copy;$('#verifier-state').textContent='EVALUATED';$('#verifier-state').style.color=color;$('#verifier-lamp').style.background=`radial-gradient(circle,${color},transparent 70%)`;$('#verifier-lamp').style.boxShadow=`0 0 48px ${color}`;const rows=[['01','Completion claim',s.claim?'Reported':'Absent',s.claim?'OBSERVED':'ABSENT'],['02','Latest action',s.success?'Succeeded':'Failed',s.success?'PASS':'FAIL'],['03','Message identifier',s.message?'Present':'Missing',s.message?'PASS':'MISSING'],['04','Recipient evidence',s.recipient?'Present':'Missing',s.recipient?'PASS':'MISSING'],['05','Later event',s.rollback?'Invalidating event':'Clear',s.rollback?'FAIL':'CLEAR']];$('#verifier-trace').innerHTML=rows.map(r=>`<li><i>${r[0]}</i><div><strong>${r[1]}</strong><p>${r[2]}</p></div><b>${r[3]}</b></li>`).join('');$('#evidence-chain').innerHTML=rows.map(r=>`<div class="${r[3]==='FAIL'?'failed':r[3]==='MISSING'||r[3]==='ABSENT'?'missing':''}"><i></i></div>`).join('')}
$$('[data-verifier-preset]').forEach(b=>b.addEventListener('click',()=>{$$('[data-verifier-preset]').forEach(x=>x.classList.remove('active'));b.classList.add('active');Object.values(vi).forEach((x,i)=>{if(x)x.checked=!!presets[b.dataset.verifierPreset][i]});evalVerifier()}));$('#run-verifier')?.addEventListener('click',evalVerifier);

function renderOutput(target,summary,cards,limitation,flow){const out=$(target);if(!out)return;out.innerHTML=`<article class="output-summary"><strong>${esc(summary)}</strong><p>${esc(limitation)}</p></article>${flow?`<div class="mini-flow">${flow.map((x,i)=>`<span class="${i===flow.length-1?'active':''}">${esc(x)}</span>`).join('')}</div>`:''}${cards.map((c,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><div><h4>${esc(c.title)}</h4><p>${esc(c.description)}</p></div><b>${esc(c.tag)}</b></article>`).join('')}`}
function buildWorkflow(){const problem=$('#workflow-problem')?.value.trim()||'The process is unclear.',risk=$('#workflow-risk')?.value||'medium',freq=$('#workflow-frequency')?.value||'daily';const approval=risk==='high'?'Named human approval before every consequential action':risk==='medium'?'Human approval before customer-facing state changes':'Periodic human review with immediate rollback';const recovery=risk==='high'?'Stop, preserve evidence and require explicit restart':risk==='medium'?'Retry once within bounds, then route to a named owner':'Retry reversible steps and log the correction';renderOutput('#workflow-output','A six-layer workflow with ownership and proof visible.',[{title:'Objective contract',description:`Translate “${problem.slice(0,100)}${problem.length>100?'…':''}” into one observable outcome and exclusions.`,tag:'OWNER'},{title:'State capture',description:'Standardise inputs, freshness, source and current owner before AI assistance begins.',tag:'INPUT'},{title:'AI assistance boundary',description:'Use AI for classification, drafting or preparation—not silent ownership of the final outcome.',tag:'ACE'},{title:'Approval gate',description:approval,tag:'CONTROL'},{title:'Evidence contract',description:'Record result, identifier, actor, timestamp and required postcondition.',tag:'PROOF'},{title:'Recovery',description:`${recovery}. Review cadence: ${freq}.`,tag:'RECOVER'}],'Structural diagnostic only; organisation-specific implementation still requires access and testing.',['Objective','Inputs','Assist','Approve','Verify','Recover'])}
$('#run-workflow')?.addEventListener('click',buildWorkflow);

const roleSets={research:[['Research Lead','Decomposes the question and defines competing hypotheses.','NO ACTION'],['Evidence Scout','Collects source-tagged evidence and freshness metadata.','READ ONLY'],['Critic','Searches for contradictions and missing evidence.','NO MUTATION'],['Synthesiser','Builds a bounded answer with uncertainty and next tests.','DRAFT ONLY']],operations:[['Workflow Strategist','Defines objective, handoffs and acceptance contract.','NO ACTION'],['Operator','Prepares or executes the allowed bounded action.','BOUNDED'],['Auditor','Compares output and observed state with the contract.','NO MUTATION'],['Recovery','Attempts a predefined reversible path after mismatch.','CONDITIONAL'],['Synthesiser','Reports verified, partial, unverified or failed.','NO OVERRIDE']],evaluation:[['Case Designer','Defines tasks, failures and acceptance fields.','NO GRADING'],['Runner','Executes conditions under controlled inputs.','SANDBOXED'],['Independent Verifier','Judges outcomes from raw evidence.','CANONICAL'],['Analyst','Computes metrics and complexity trade-offs.','READ ONLY']],delivery:[['Requirements Lead','Extracts audience, use case and completion standard.','NO ACTION'],['Builder','Creates the requested artefact.','DRAFT/BUILD'],['Reviewer','Checks accuracy, accessibility and boundaries.','NO MUTATION'],['Release Gate','Approves only the verified output.','HUMAN']]};
function buildAgents(){const task=$('#agent-task')?.value||'operations',risk=$('#agent-risk')?.value||'medium',aut=$('#agent-autonomy')?.value||'prepare';const roles=[...roleSets[task]];if(risk==='high')roles.push(['Human Risk Owner','Approves exceptions and any expansion of authority.','FINAL']);if(aut==='execute'&&risk!=='low')roles.push(['Policy Gate','Blocks actions outside allowed scope, recipient, amount or time.','PRE-ACTION']);const boundary=aut==='assist'?'No external action; analysis and drafting only.':aut==='prepare'?'Actions are prepared for named human approval.':risk==='low'?'Only reversible bounded actions may execute automatically.':'Execution requires policy checks and retained human authority.';renderOutput('#agent-output',`${roles.length} roles, added only where separation improves control or evidence.`,roles.map(r=>({title:r[0],description:r[1],tag:r[2]})),`${boundary} This is an architecture proposal, not a production claim.`,roles.map(r=>r[0].replace('Workflow ','').replace('Independent ','')))}
$('#run-agents')?.addEventListener('click',buildAgents);

function buildEvidence(){const claim=$('#claim-input')?.value.trim()||'The system performs better.',scope=$('#claim-scope')?.value||'comparative';const req={demo:'A deterministic fixture can support a narrow software-behaviour claim.',comparative:'Both conditions need identical tasks, tools, evidence rules, mutation limits and paired analysis.',production:'Representative live traffic, pre-registered metrics, sufficient sample size, latency, cost, safety and incident data are required.'}[scope];const conclusion=scope==='production'?'Current deterministic evidence is insufficient for a production-performance claim.':'The claim is testable if the contract is fixed before results are observed.';renderOutput('#evidence-output',`Evidence contract for: “${claim.slice(0,115)}${claim.length>115?'…':''}”`,[{title:'Operational definition',description:'Replace vague words with a measurable outcome, denominator and window.',tag:'DEFINE'},{title:'Acceptance contract',description:'Lock action, evidence fields, event semantics and valid states before testing.',tag:'LOCK'},{title:'Independent observation',description:'Preserve raw traces and external postconditions separately from the system report.',tag:'OBSERVE'},{title:'Fair comparison',description:req,tag:'CONTROL'},{title:'Falsification rule',description:'State what result or missing field would force the claim to be weakened or rejected.',tag:'CHALLENGE'},{title:'Bounded conclusion',description:conclusion,tag:'REPORT'}],'A proof plan can reveal that evidence is missing; it cannot manufacture the evidence.',['Claim','Define','Observe','Challenge','Conclude'])}
$('#run-evidence')?.addEventListener('click',buildEvidence);

const plans={evaluate:{'48h':['Failure-surface interview','Initial acceptance contract','Ten representative cases','Evidence and risk memo'],'2w':['Evaluation harness prototype','Structured case suite','Trace and metric design','Reproducible findings report'],'6w':['Shadow evaluation pipeline','Live-model comparison plan','Reviewer workflow','Scale / redesign / stop decision']},workflow:{'48h':['Process and handoff map','Automation opportunity screen','Risk and ownership matrix','Pilot recommendation'],'2w':['Narrow workflow prototype','Approval and recovery gates','Evidence logging','Operational test plan'],'6w':['Shadow pilot','Exception monitoring','Human-review measurement','Implementation runbook']},research:{'48h':['Question decomposition','Evidence register','Competing explanations','Next-test recommendation'],'2w':['Structured source review','Claim map','Prototype calculation or simulation','Decision-ready synthesis'],'6w':['Repeatable research pipeline','External review loop','Experiment design','Validated research roadmap']},prototype:{'48h':['Requirements and claim boundary','Interaction or architecture concept','Feasibility memo','Build sequence'],'2w':['Working narrow prototype','Core tests','Interactive demonstration','Technical and limitation documentation'],'6w':['Shadow-ready pilot','Telemetry and failure handling','Reviewer feedback cycle','Production-readiness decision']}};
function buildDelivery(){const goal=$('#delivery-goal')?.value||'prototype',h=$('#delivery-horizon')?.value||'2w',team=$('#delivery-team')?.value||'product',items=plans[goal][h];const ctx={founder:'Optimise for one decision and minimal overhead.',product:'Integrate product, engineering and reviewer needs.',operations:'Prioritise ownership, handoffs and exceptions.',governance:'Prioritise provenance, policy boundaries and reviewability.'}[team];const label={'48h':'48-hour diagnostic','2w':'two-week prototype','6w':'six-week shadow pilot'}[h];renderOutput('#delivery-output',`${label}: four concrete outputs and one decision point.`,items.map((x,i)=>({title:x,description:`${ctx} ${i===items.length-1?'Finish with a named owner and next decision.':'Keep claims bounded by evidence available at this stage.'}`,tag:i===items.length-1?'DECIDE':`OUTPUT ${i+1}`})),'Actual scope depends on access to systems, data, stakeholders and constraints.',['Discover','Define','Build','Test','Decide'])}
$('#run-delivery')?.addEventListener('click',buildDelivery);

function addSocialFooter(){const footer=$('.footer-inner');if(!footer||$('.footer-socials',footer))return;const socials=document.createElement('nav');socials.className='footer-socials';socials.setAttribute('aria-label','Social profiles');socials.innerHTML='<a href="https://www.linkedin.com/in/luca-panayiotou-64936b256/" target="_blank" rel="noreferrer noopener" aria-label="Luca Panayiotou on LinkedIn">LinkedIn</a>';const note=$('p',footer);if(note)footer.insertBefore(socials,note);else footer.append(socials)}
const modal=$('[data-cv-modal]');let prev=null;function openCV(){if(!modal)return;prev=document.activeElement;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';$('[data-close-cv]',modal)?.focus()}function closeCV(){if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';prev?.focus?.()}$$('[data-open-cv]').forEach(b=>b.addEventListener('click',openCV));$$('[data-close-cv]').forEach(b=>b.addEventListener('click',closeCV));$('#print-cv')?.addEventListener('click',()=>print());addEventListener('keydown',e=>{if(e.key==='Escape'){closeCV();nav?.classList.remove('open');menu?.setAttribute('aria-expanded','false')}});
showCommand('direction');showRole('evaluation');evalVerifier();buildWorkflow();buildAgents();buildEvidence();buildDelivery();addSocialFooter();