(()=>{
  const qs=(s,c=document)=>c.querySelector(s);const qsa=(s,c=document)=>[...c.querySelectorAll(s)];
  if(qs('#flagship'))return;
  const css=document.createElement('link');css.rel='stylesheet';css.href='flagship.css';document.head.append(css);

  const nav=qs('[data-nav]');
  if(nav&&!qs('a[href="#flagship"]',nav)){
    const link=document.createElement('a');link.href='#flagship';link.textContent='Case study';
    const workLink=qs('a[href="#work"]',nav);nav.insertBefore(link,workLink||nav.firstChild);
  }

  const flagship=document.createElement('section');
  flagship.id='flagship';flagship.className='flagship-case';
  flagship.innerHTML=`
    <div class="case-stage">
      <div class="shell case-stage-grid">
        <div class="case-story">
          <p class="case-kicker">Flagship case study · Agent Completion Verifier</p>
          <h2>Most AI systems can say they finished.<br><em>Far fewer can prove it.</em></h2>
          <p class="case-lead">A model-agnostic evaluator that separates an agent's completion claim from independently observable evidence, then resolves the result against a fixed acceptance contract.</p>
          <div class="case-actions">
            <button class="button button-primary" type="button" data-open-case-layer="problem">See the technical evidence</button>
            <a class="button" href="index.html#lab">Open interactive verifier</a>
            <a class="button" href="https://github.com/Luca-1304/agent-reliability-arena" target="_blank" rel="noopener noreferrer">Inspect public source</a>
          </div>
          <p class="case-boundary">Public results use controlled deterministic fixtures. They are evidence of the implemented software behaviour, not a claim of universal production performance.</p>
        </div>
        <div class="verdict-cinema" aria-label="Completion claim passing through an evidence gate to a verified verdict">
          <div class="cinema-grid" aria-hidden="true"></div>
          <div class="claim-node"><small>AGENT REPORT</small><strong>TASK COMPLETE</strong><span>Source-reported claim</span></div>
          <div class="trace-line trace-a" aria-hidden="true"><i></i></div>
          <div class="evidence-gate">
            <small>ACCEPTANCE CONTRACT</small>
            <div><span>Action</span><b>PASS</b></div><div><span>Identifier</span><b>PASS</b></div><div><span>Destination</span><b>PASS</b></div><div><span>Later event</span><b>CLEAR</b></div>
          </div>
          <div class="trace-line trace-b" aria-hidden="true"><i></i></div>
          <div class="verdict-node"><small>CANONICAL VERDICT</small><strong>VERIFIED_<br>COMPLETE</strong><span>Independent judgement</span></div>
        </div>
      </div>
      <div class="shell case-metric-strip" aria-label="Controlled fixture results">
        <article><small>VERIFIED OUTCOMES</small><strong>2/8 → 6/8</strong><span>Same eight controlled cases</span></article>
        <article><small>FALSE COMPLETIONS</small><strong>3 → 0</strong><span>Unsupported success claims</span></article>
        <article><small>CLAIM PRECISION</small><strong>0.25 → 1.00</strong><span>Within the reference fixture</span></article>
        <article><small>RECOVERED CASES</small><strong>4</strong><span>Mismatch paths recovered</span></article>
        <article><small>PYTHON RANGE</small><strong>3.10–3.13</strong><span>Verified release range</span></article>
      </div>
    </div>

    <div class="shell case-technical">
      <div class="case-heading">
        <p class="section-index">Technical underneath</p>
        <h2>Every visual resolves into something inspectable.</h2>
        <p>Open each layer to move from the operational failure to the architecture, representative trace, measured result and honest limitation.</p>
      </div>
      <div class="case-layer-list">
        <article class="case-layer open" id="case-problem" data-case-layer="problem">
          <button type="button" aria-expanded="true"><span>01</span><div><small>OPERATIONAL FAILURE</small><h3>The system can sound finished while reality is incomplete.</h3></div><b>−</b></button>
          <div class="case-layer-body">
            <div class="technical-copy"><p>A successful tool receipt may prove that one action occurred without proving the requested outcome. Required fields can be absent, partial evidence can be promoted to completion, and a later rollback can make an earlier success stale.</p><blockquote>Completion is not a sentence generated by the system. It is a judgement against observable state.</blockquote></div>
            <div class="failure-surface"><article><span>CLAIM</span><strong>“Done.”</strong><p>Fluent output from the actor under test.</p></article><article><span>MISSING</span><strong>No destination proof</strong><p>The requested recipient or external state is unobserved.</p></article><article><span>RISK</span><strong>False completion</strong><p>A downstream process trusts a state that does not exist.</p></article></div>
          </div>
        </article>

        <article class="case-layer" id="case-insight" data-case-layer="insight">
          <button type="button" aria-expanded="false"><span>02</span><div><small>DESIGN PRINCIPLE</small><h3>Fix the acceptance contract before observing the answer.</h3></div><b>+</b></button>
          <div class="case-layer-body" hidden><div class="insight-statement"><p>Completion must be judged against a fixed acceptance contract and independently observable state, not the system's own confidence or wording.</p></div><div class="contract-grid"><article><small>REQUIRED ACTION</small><strong>What must actually happen?</strong></article><article><small>EVIDENCE FIELDS</small><strong>Which identifiers and postconditions prove it?</strong></article><article><small>EVENT SEMANTICS</small><strong>Which event is latest and still valid?</strong></article><article><small>VERDICT STATES</small><strong>Verified, partial, unverified or failed.</strong></article></div></div>
        </article>

        <article class="case-layer" id="case-architecture" data-case-layer="architecture">
          <button type="button" aria-expanded="false"><span>03</span><div><small>SYSTEM ARCHITECTURE</small><h3>Separate execution, evidence and judgement.</h3></div><b>+</b></button>
          <div class="case-layer-body" hidden>
            <div class="architecture-map" aria-label="Agent Completion Verifier architecture">
              <article><i>01</i><strong>Task contract</strong><span>Required action, evidence and valid states</span></article><article><i>02</i><strong>Agent under test</strong><span>Produces actions, traces and claims</span></article><article><i>03</i><strong>Raw trace</strong><span>Preserved source events without grading</span></article><article><i>04</i><strong>Evidence normaliser</strong><span>Maps tool-specific fields into one schema</span></article><article><i>05</i><strong>Independent verifier</strong><span>Compares evidence with the fixed contract</span></article><article><i>06</i><strong>Canonical verdict</strong><span>One explicit completion state</span></article><article><i>07</i><strong>Replay record</strong><span>Trace, limitations and reproducible judgement</span></article>
            </div>
            <div class="architecture-note"><strong>Boundary</strong><p>The agent producing the action never silently redefines the proof standard after it acts.</p></div>
          </div>
        </article>

        <article class="case-layer" id="case-trace" data-case-layer="trace">
          <button type="button" aria-expanded="false"><span>04</span><div><small>REPRESENTATIVE TRACE</small><h3>Show exactly why the verdict was reached.</h3></div><b>+</b></button>
          <div class="case-layer-body" hidden>
            <div class="trace-table" role="table" aria-label="Representative completion evidence trace">
              <div class="trace-head" role="row"><span>Observation</span><span>Raw state</span><span>Judgement</span></div>
              <div role="row"><strong>Completion claim</strong><span>Reported: “Task complete”</span><b class="observed">OBSERVED</b></div>
              <div role="row"><strong>Latest required action</strong><span>Successful delivery event</span><b class="pass">PASS</b></div>
              <div role="row"><strong>Message identifier</strong><span>msg_4a91 present</span><b class="pass">PASS</b></div>
              <div role="row"><strong>Destination evidence</strong><span>Required recipient matched</span><b class="pass">PASS</b></div>
              <div role="row"><strong>Later invalidating event</strong><span>No rollback observed</span><b class="clear">CLEAR</b></div>
              <div role="row" class="trace-verdict"><strong>Canonical state</strong><span>All required evidence remains valid</span><b>VERIFIED_COMPLETE</b></div>
            </div>
            <pre class="code-excerpt" aria-label="Illustrative verdict state handling"><code>if latest_event.invalidates_success:
    return FAILED
if action_ok and required_evidence.complete:
    return VERIFIED_COMPLETE
if action_ok and required_evidence.partial:
    return PARTIAL
return UNVERIFIED</code></pre>
          </div>
        </article>

        <article class="case-layer" id="case-results" data-case-layer="results">
          <button type="button" aria-expanded="false"><span>05</span><div><small>CONTROLLED RESULTS</small><h3>Measure the behavioural difference without inflating the claim.</h3></div><b>+</b></button>
          <div class="case-layer-body" hidden>
            <div class="comparison-scene"><div><small>GENERAL CONDITION</small><strong>2<sup>/8</sup></strong><span>independently verified</span></div><i>VS</i><div><small>SPECIALIST CONDITION</small><strong>6<sup>/8</sup></strong><span>independently verified</span></div></div>
            <div class="result-notes"><article><strong>3 → 0</strong><span>False-completion claims in the controlled fixture</span></article><article><strong>0.25 → 1.00</strong><span>Claim precision within the same fixture</span></article><article><strong>4</strong><span>Recovered mismatch scenarios</span></article><article><strong>3.10–3.13</strong><span>Python release verification range</span></article></div>
            <p class="result-boundary">Denominator: eight paired deterministic cases under fixed task, tool and evidence rules. The result supports a narrow software-behaviour claim, not universal model superiority.</p>
          </div>
        </article>

        <article class="case-layer" id="case-limitations" data-case-layer="limitations">
          <button type="button" aria-expanded="false"><span>06</span><div><small>LIMITATIONS & NEXT TEST</small><h3>Make the boundary as visible as the result.</h3></div><b>+</b></button>
          <div class="case-layer-body" hidden>
            <div class="limits-grid"><article><strong>Deterministic fixture</strong><p>Not representative production traffic.</p></article><article><strong>No universal claim</strong><p>Does not prove performance across every model or workflow.</p></article><article><strong>No live mutation</strong><p>The public demonstration changes no external state.</p></article><article><strong>Operational validation required</strong><p>Real impact needs representative tasks, systems and postconditions.</p></article><article><strong>Complexity disclosed</strong><p>Specialist roles add logical role-call overhead.</p></article></div>
            <div class="next-test"><small>NEXT EMPIRICAL STEP</small><strong>Run the same acceptance contract against representative live-model traces and organisation-specific postconditions.</strong></div>
          </div>
        </article>
      </div>
    </div>
  `;

  const skim=qs('#skim');skim?.insertAdjacentElement('afterend',flagship);

  const why=document.createElement('section');why.id='why-luca';why.className='why-luca';why.innerHTML=`<div class="shell why-grid"><div><p class="section-index">Why Luca</p><h2>Built from consequence, not only abstraction.</h2><p class="why-lead">I did not enter AI through a conventional software-engineering ladder. I came through insurance operations, safety-critical work, customer consequence and practical delivery. That background makes me naturally suspicious of systems that look complete but fail in reality.</p></div><div class="why-links"><article><span>INSURANCE OPERATIONS</span><strong>Information accuracy and customer consequence</strong></article><article><span>FIRE SAFETY</span><strong>Procedure, escalation and evidence</strong></article><article><span>PRACTICAL DELIVERY</span><strong>Changing conditions and accountability</strong></article><article><span>AI-ASSISTED BUILDING</span><strong>Rapid experimentation with explicit boundaries</strong></article></div></div>`;
  flagship.insertAdjacentElement('afterend',why);

  const roles=document.createElement('section');roles.id='role-coverage';roles.className='preview-roles';roles.innerHTML=`<div class="shell"><div class="section-head"><p class="section-index">Role coverage</p><h2>Where this way of working becomes useful.</h2><p>Realistic role families, ordered by the evidence currently available rather than inflated seniority.</p></div><div class="preview-role-grid"><article><small>STRONGEST FIT</small><h3>AI Evaluation / Quality Analyst</h3><p>Acceptance contracts, case design, trace review and failure analysis.</p></article><article><small>STRONG FIT</small><h3>Applied AI / Automation Specialist</h3><p>Bounded workflow prototypes, approval gates and evidence-led iteration.</p></article><article><small>STRONG FIT</small><h3>Technical Operations Analyst</h3><p>Process discovery, ownership, handoffs and measurable improvement.</p></article><article><small>CREDIBLE FIT</small><h3>AI Product / Solutions Associate</h3><p>Problem shaping, demonstrations and honest capability boundaries.</p></article></div><a class="button" href="index.html#roles">Open the full role map</a></div>`;
  why.insertAdjacentElement('afterend',roles);

  const publicWork=document.createElement('section');publicWork.id='public-work';publicWork.className='public-work';publicWork.innerHTML=`<div class="shell"><div class="section-head"><p class="section-index">Public work & artefacts</p><h2>Objects another person can inspect.</h2><p>The portfolio is strongest when claims resolve into code, traces, tests and explicit limitations.</p></div><div class="artefact-grid"><a href="https://github.com/Luca-1304/agent-reliability-arena" target="_blank" rel="noopener noreferrer"><small>PUBLIC REPOSITORY</small><h3>Agent Reliability Arena</h3><p>Controlled cases, evaluation logic and public implementation history.</p><span>Inspect source →</span></a><a href="index.html#lab"><small>INTERACTIVE ARTEFACT</small><h3>Completion Verifier</h3><p>Change evidence fields and observe the canonical completion state.</p><span>Run verifier →</span></a><a href="index.html#evidence"><small>RESULT BOUNDARY</small><h3>Controlled comparison</h3><p>Metrics, denominators, limitations and role-call complexity shown together.</p><span>Review evidence →</span></a><a href="interests.html"><small>WORKING METHOD</small><h3>Interests & ACE</h3><p>The questions, collaboration style and public boundary behind the work.</p><span>Explore method →</span></a></div></div>`;
  roles.insertAdjacentElement('afterend',publicWork);

  const contactTitle=qs('#contact h2');if(contactTitle)contactTitle.textContent='Give me a problem your team has not been able to make measurable.';
  const contactCopy=qs('#contact .contact-copy>p:not(.section-index)');if(contactCopy)contactCopy.textContent='I will help separate the real objective, the evidence standard, the failure surface and the smallest useful test—whether the route is a role, contract, subcontract engagement or selected technical project.';

  function setLayer(key,scroll=false){
    qsa('[data-case-layer]').forEach(layer=>{const on=layer.dataset.caseLayer===key;layer.classList.toggle('open',on);const button=qs(':scope>button',layer);const body=qs('.case-layer-body',layer);button?.setAttribute('aria-expanded',String(on));if(button){const icon=qs(':scope>b',button);if(icon)icon.textContent=on?'−':'+'}if(body)body.hidden=!on});
    if(scroll)qs(`[data-case-layer="${key}"]`)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});
    history.replaceState(null,'',`#case-${key}`);
  }
  qsa('[data-case-layer]>button').forEach(button=>button.addEventListener('click',()=>{const layer=button.closest('[data-case-layer]');setLayer(layer.dataset.caseLayer)}));
  qsa('[data-open-case-layer]').forEach(button=>button.addEventListener('click',()=>setLayer(button.dataset.openCaseLayer,true)));
  const hash=location.hash.replace('#case-','');if(['problem','insight','architecture','trace','results','limitations'].includes(hash))setLayer(hash);
})();
